name: Bilibili Daily Checkin

on:
  schedule:
    - cron: '18 18 * * *'  # UTC时间每天18:18点执行(对应CST时间 2:18)
  workflow_dispatch:  # 支持手动触发

jobs:
  run-bilibili-task:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests loguru
          
      - name: Execution Information
        env:
          BILIBILI_COOKIE: ${{ secrets.BILIBILI_COOKIE }}
        run: python auto_task.py
